### ISSUE TITLE
Use Senzing POC Server's bulk load via RabbitMQ functionality

### ISSUE THREAD

**Issue by docktermj** [Senzing/entity-search-web-app#233]
In testing done for https://github.com/Senzing/docker-compose-demo/issues/211, it seems that the Senzing POC Server is not being called to import bulk data via RabbitMQ.

**Comment by arawinters** [comment]
While debugging a separate issue(#235) I was running in to a very strange issue. All my **SQS** related variables were set(see below) but the Web App was disabling Stream Loading. Upon further investigation it turns  out the the **Poc Server** was sending back `loadQueueConfigured":false` (check in `/server-info` for the poc server) which the web app checks at startup and if that is set to _**false**_ it does not set up web socket proxy.

## SQS variables being set locally that result in disabled SQS support
```
environment:
#     See https://github.com/Senzing/senzing-api-server#configuration
      SENZING_DATABASE_URL: "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-senzing-post>
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      AWS_REGION: ${AWS_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      SENZING_SQS_QUEUE_URL: ${SENZING_SQS_QUEUE_URL}
```
This used to work so I'm not sure if the variables have changed or if I'm missing something @barrycaceres?
If I set a command line input to the same value as the `SENZING_SQS_QUEUE_URL` variable it works correctly.
```
- --sqs-load-url
      - https://sqs.us-west-2.amazonaws.com/528659257769/ara-queue
```
